### ISSUE TITLE
FIXME: declarar como CONST

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#10]
string Consolidado::getSexo()

--> This function should be declared "const". <--

{
    return sexo;
}

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: FUNCIONES GETTERS EN EL CONSOLIDADO .H Y .CPP DECLARADAS CONST.

    int getIdSexo() const;
    void setIdSexo(int);

    string getSexo() const;
    void setSexo(string &);

    int getAno() const;
    void setAno(int);

    int getSemestre() const;
    void setSemestre(int);

    int getInscritos() const;
    void setInscritos(int);

    int getAdmitidos() const;
    void setAdmitidos(int);

    int getMatriculados() const;
    void setMatriculados(int);

    int getMatriculadosPrimerSemestre() const;
    void setMatriculadosPrimerSemestre(int);

    int getGraduados() const;
    void setGraduados(int);
