### ISSUE TITLE
FIXME: Revisar los comentarios basura/innecesarios del código

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#12]
ej:

// NEW quitar estas variables de aquí y del constructor del SNIESController
    //  estas constantes las leerá el SNIESController del archivo de Settings.h
    //  Completar el archivo con el resto de constantes necesarias <--

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: ELIMINACION DE COMENTARIOS INNECESARIOS.
