### ISSUE TITLE
FIXME: Agregar const a los métodos getters en consolidado.cpp

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#13]
int Consolidado::getSemestre()

---> This function should be declared "const". <----

{
    return semestre;
}

**Comment by anadan10102006** [comment]
ISSUE SOLVED: SE AGREGA CONST A LOS METODOS GETTERS DEL CONSOLIDADO


    int getIdSexo() const;
    void setIdSexo(int);

    string getSexo() const;
    void setSexo(string &);

    int getAno() const;
    void setAno(int);

    int getSemestre() const;
    void setSemestre(int);

    int getInscritos() const;
    void setInscritos(int);

    int getAdmitidos() const;
    void setAdmitidos(int);

    int getMatriculados() const;
    void setMatriculados(int);

    int getMatriculadosPrimerSemestre() const;
    void setMatriculadosPrimerSemestre(int);

    int getGraduados() const;
    void setGraduados(int);
