### ISSUE TITLE
FIXME: pasar por referencia "etiquetas columnas" en GestorJson.cpp

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#14]
bool GestorJson::crearArchivo(string &ruta, map<int, ProgramaAcademico *> &mapadeProgramasAcademicos, vector<string> etiquetasColumnas)

--> Pass expensive to copy object "etiquetasColumnas" by reference to const.

**Comment by anadan10102006** [comment]
ISSUE SOLVED: SE AJUSTO LA FUNCION EN LA CLASE PADRE E HIJAS PARA QUE SE PASE EL VECTOR POR REFERENCIA.


GESTOR.H

virtual bool crearArchivo(string &ruta, map<int, ProgramaAcademico *> &mapadeProgramasAcademicos, vector<string> &etiquetasColumnas) = 0;

GESTORJSON.H

bool crearArchivo(string &ruta, map<int, ProgramaAcademico *> &mapadeProgramasAcademicos, vector<string> &etiquetasColumnas) override;
