### ISSUE TITLE
FIXME: Convert string literal to raw string literal (Gestor Json)

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#15]
--> Aquí:

archivoBuscados << "        \"area_de_conocimiento\": \"" << (*it)->getAreaDeConocimiento() << "\"," << endl;

**Comment by anadan10102006** [comment]
ISSUE RESOLVED:  CAMBIO DE STRING LITERAL A RAW STRING LITERAL EN LAS FUNCIONES DEL JSON .CPP

            archivoBuscados << R"(        "codigo_de_la_institucion": ")" << (*it)->getCodigoDeLaInstitucion() << "\"," << endl;
            archivoBuscados << R"(        "ies_padre": ")" << (*it)->getIesPadre() << "\"," << endl;
            archivoBuscados << R"(        "institucion_de_educacion_superior": ")" << (*it)->getInstitucionDeEducacionSuperiorIes() << "\"," << endl;
            archivoBuscados << R"(        "principal_o_seccional": ")" << (*it)->getPrincipalOSeccional() << "\"," << endl;
            archivoBuscados << R"(        "id_sector": ")" << (*it)->getIdSectorIes() << "\"," << endl;
            archivoBuscados << R"(        "sector": ")" << (*it)->getSectorIes() << "\"," << endl;
            archivoBuscados << R"(        "id_caracter": ")" << (*it)->getIdCaracter() << "\"," << endl;
            archivoBuscados << R"(        "caracter": ")" << (*it)->getCaracterIes() << "\"," << endl;
            archivoBuscados << R"(        "codigo_departamento": ")" << (*it)->getCodigoDelDepartamentoIes() << "\"," << endl;
            archivoBuscados << R"(        "departamento_domicilio": ")" << (*it)->getDepartamentoDeDomicilioDeLaIes() << "\"," << endl;
            archivoBuscados << R"(        "codigo_municipio": ")" << (*it)->getCodigoDelMunicipioIes() << "\"," << endl;
            archivoBuscados << R"(        "municipio_domicilio": ")" << (*it)->getMunicipioDeDomicilioDeLaIes() << "\"," << endl;
            archivoBuscados << R"(        "codigo_snies_programa": ")" << (*it)->getCodigoSniesDelPrograma() << "\"," << endl;
            archivoBuscados << R"(        "programa_academico": ")" << (*it)->getProgramaAcademico() << "\"," << endl;
            archivoBuscados << R"(        "id_nivel_academico": ")" << (*it)->getIdNivelAcademico() << "\"," << endl;
            archivoBuscados << R"(        "nivel_academico": ")" << (*it)->getNivelAcademico() << "\"," << endl;
            archivoBuscados << R"(        "id_nivel_formacion": ")" << (*it)->getIdNivelDeFormacion() << "\"," << endl;
            archivoBuscados << R"(        "nivel_formacion": ")" << (*it)->getNivelDeFormacion() << "\"," << endl;
            archivoBuscados << R"(        "id_metodologia": ")" << (*it)->getIdMetodologia() << "\"," << endl;
            archivoBuscados << R"(        "metodologia": ")" << (*it)->getMetodologia() << "\"," << endl;
            archivoBuscados << R"(        "id_area": ")" << (*it)->getIdArea() << "\"," << endl;
            archivoBuscados << R"(        "area_de_conocimiento": ")" << (*it)->getAreaDeConocimiento() << "\"," << endl;
            archivoBuscados << R"(        "id_nucleo": ")" << (*it)->getIdNucleo() << "\"," << endl;
            archivoBuscados << R"(        "nucleo_basico": ")" << (*it)->getNucleoBasicoDelConocimientoNbc() << "\"," << endl;
            archivoBuscados << R"(        "id_cine_campo_amplio": ")" << (*it)->getIdCineCampoAmplio() << "\"," << endl;
            archivoBuscados << R"(        "desc_cine_campo_amplio": ")" << (*it)->getDescCineCampoAmplio() << "\"," << endl;
            archivoBuscados << R"(        "id_cine_campo_especifico": ")" << (*it)->getIdCineCampoEspecifico() << "\"," << endl;
            archivoBuscados << R"(        "desc_cine_campo_especifico": ")" << (*it)->getDescCineCampoEspecifico() << "\"," << endl;
            archivoBuscados << R"(        "id_cine_codigo_detallado": ")" << (*it)->getIdCineCodigoDetallado() << "\"," << endl;
            archivoBuscados << R"(        "desc_cine_codigo_detallado": ")" << (*it)->getDescCineCodigoDetallado() << "\"," << endl;
            archivoBuscados << R"(        "codigo_departamento_programa": ")" << (*it)->getCodigoDelDepartamentoPrograma() << "\"," << endl;
            archivoBuscados << R"(        "departamento_oferta_programa": ")" << (*it)->getDepartamentoDeOfertaDelPrograma() << "\"," << endl;
            archivoBuscados << R"(        "codigo_municipio_programa": ")" << (*it)->getCodigoDelMunicipioPrograma() << "\"," << endl;
            archivoBuscados << R"(        "municipio_oferta_programa": ")" << (*it)->getMunicipioDeOfertaDelPrograma() << "\"," << endl;
