### ISSUE TITLE
FIXME: SNIESController cpp, arreglar bucle.

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#17]
Clang-Tidy: Use range-based for loop instead 

for (map<int, ProgramaAcademico *>::iterator it = programasAcademicos.begin(); it != programasAcademicos.end(); ++it)
    {
    Línea 413

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: CAMBIO DE LA DECLARACION DEL ITERADOR USANDO AUTO.

for (auto it = programasAcademicos.begin(); it != programasAcademicos.end(); ++it)
