### ISSUE TITLE
FIXME: Change raw-loop (gestorTXT)

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#19]
for (int i = 0; i < etiquetasColumnas.size(); i++)
Change this raw for-loop to a range for-loop or an "std::ranges::for_each".
(LINEA 97)

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: BUCLE CONVERTIDO EN UN BUCLE BASADO EN RANGO.

for (const auto &etiqueta : etiquetasColumnas) {
            archivoBuscados << etiqueta << "\t"; 
        }
