### ISSUE TITLE
FIXME: Pasar parámetro por referencia; GestorCSV

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#21]
vector<int> GestorCsv::leerProgramasCsv(string &ruta)
Make the type of this parameter a reference-to-const. The current type of "ruta" is "std::string &".

{

**Comment by anadan10102006** [comment]
ISSUE SOLVED: SE DECLARO LA VARIABLE POR REFERENCIA COMO UNA CONSTANTE. SOLUCIONADO EN GESTORCSV .H Y .CPP

vector<int> leerProgramasCsv(const string &ruta);
