### ISSUE TITLE
FIXME: Reemplazar el redundant type

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#22]
vector<int> GestorCsv::leerProgramasCsv(string &ruta)
Make the type of this parameter a reference-to-const. The current type of "ruta" is "std::string &".

{

(View.cpp)

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: PARAMETRO CONVERTIDO A CONST.

vector<int> leerProgramasCsv(const string &ruta);
