### ISSUE TITLE
FIXME: Use init statement

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#23]
int main() {
    View menu;
    
bool archivosParametrizados = menu.mostrarPantallaBienvenido();
New code
    if (archivosParametrizados) {

--> Use the init-statement to declare "archivosParametrizados" inside the if statement. <--

Línea 6, main.cpp

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: SE DECLARA EL PARAMETRO DENTRO DEL IF.

int main() {
    View menu;
    
    if (bool archivosParametrizados = menu.mostrarPantallaBienvenido()) {
        menu.mostrarDatosExtra();
        menu.buscarPorPalabraClaveYFormacion();
    }
