### ISSUE TITLE
FIXME: Usar Array de C++, en vez de C. 

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#24]
Consolidado *consolidado[Settings::DATOS_ACADEM_DEMOGRAF];
Use "std::array" or "std::vector" instead of a C-style array.

Línea 114, Controller.cpp

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: USO DE STD::VECTOR EN VEZ DE C-STYLE ARRAY

vector<Consolidado*> consolidado(Settings::DATOS_ACADEM_DEMOGRAF);
