### ISSUE TITLE
FIXME: Declaration shadows a field of "Consolidado"

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#25]
void Consolidado::setSexo(string &sexo)
declaration shadows a field of 'Consolidado'

-->la clase Consolidado probablemente tiene un atributo llamado sexo, y el parámetro de la función setSexo se llama también sexo. Esto causa un conflicto, ya que dentro del cuerpo de la función, el nombre sexo se refiere al parámetro de la función y no al atributo de la clase.

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: CAMBIO DEL NOMBRE DEL PARAMETRO QUE RECIBE LA FUNCION.

void Consolidado::setSexo(string &sex)
{
    this->sexo = sex;
}
