### ISSUE TITLE
FIXME: Declarar variable dentro del bucle

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#26]
map<int, ProgramaAcademico *>::iterator it;
        // Leemos todos los programas del mapa para imprimirlos en el archivo
        for (it = mapadeProgramasAcademicos.begin(); it != mapadeProgramasAcademicos.end(); it++)

--> Declare the variable "it" inside the loop. <--

GestorCsv, Línea 322

**Comment by anadan10102006** [comment]
ISSUE SOLVED: ITERADOR INICIALIZADO EN EL BUCLE.

for (map<int, ProgramaAcademico *>::iterator it = mapadeProgramasAcademicos.begin(); it != mapadeProgramasAcademicos.end(); it++)
