### ISSUE TITLE
FIXME : parámetros en el constructor de consolidado

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#7]
Consolidado::Consolidado() = default;
Consolidado::Consolidado(int idSexo, string sexo, int ano, int semestre, int inscritos, int admitidos, int primeraMatricula, 
int totalMatriculados, 
int graduados)

--> This function has 9 parameters, which is greater than the 7 authorized <--

    : idSexo(idSexo), sexo(sexo), ano(ano), semestre(semestre), inscritos(inscritos), admitidos(admitidos), matriculados(primeraMatricula), matriculadosPrimerSemestre(totalMatriculados), graduados(graduados) {}

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: AJUSTE DE LOS PARAMETROS EN LA FUNCION EN EL .H DE CONSOLIDADO.

Consolidado(int, string, int, int, int, int, int, int, int)
