### ISSUE TITLE
FIXME : Quitar las constantes del constructor de VIEW

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#8]
View::View()
{
    string ruta1 = string("inputs/programas.csv");
    string ruta2 = string("inputs/admitidos");
    string ruta3 = string("inputs/graduados");
    string ruta4 = string("inputs/inscritos");
    string ruta5 = string("inputs/matriculados");
    string ruta6 = string("inputs/matriculadosPrimerSemestre");
    string ruta7 = string("outputs/");
    controlador = SNIESController(ruta1, ruta2, ruta3, ruta4, ruta5, ruta6, ruta7);
}

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: SE QUITARON LAS CONSTANTES DEL VIEW PARA USAR LAS DIRECCIONES GUARDADAS EN SETTINGS.

View::View()
{
    controlador = SNIESController();
}
