### ISSUE TITLE
FIXME: Atenerse a sintaxis de constantes

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-4-beibis-1#9]
Cambiar constante "delimitador" por "DELIMITADOR" en Settings.cpp y Settings.h

**Comment by anadan10102006** [comment]
ISSUE RESOLVED: CAMBIO DEL NOMBRE DE LA CONSTANTE EN .H Y .CPP, ADEMAS DE LOS LUGARES DEL CODIGO DONDE ES LLAMADA.

SETTINGS.H
static const char DELIMITADOR;

SETTINGS.CPP
const char Settings::DELIMITADOR = ';';
